export const EXCEPTION = {
  USER_ALREADY_EXISTS: 'User already exists',
  USER_NOT_FOUND: 'User not found',
  INVALID_TOKEN: 'Invalid token',
  INVALID_CREDENTIALS: 'Email or password is invalid',
  AIRCRAFT_ALREADY_EXISTS: 'Aircraft already exists',
  AIRCRAFT_NOT_FOUND: 'Aircraft not found',
  HANGAR_NOT_FOUND: 'Hangar not found',
  AIRPORT_NOT_FOUND: 'Airport not found',
  RESERVATION_NOT_FOUND: 'Reservation not found',
  PHONE_ALREADY_EXISTS: 'User with this phone already exists',
  PASSWORD_INVALID: 'Password invalid',
  PASSWORDS_MISMATCH: 'Passwords mismatch',
  PAYMENT_NOT_FOUND: 'Payment not found',
  UTILITIES_NOT_FOUND: 'Utilities not found',
  OFFICE_NOT_FOUND: 'Office not found',
};
